### ISSUE TITLE
The to-do-issue

### ISSUE THREAD

**Issue by johangroe** [johangroe/easyserver#1]
***This contains every to-do I encounter during making this project!***
It's wayy more detailed than the README.md in the repo.

**functionality to-do's** (those are to-do's that need to be done, to let the webserver function properly, it's actual mainly the development of the logic's 'n' stuff):

- [x] 1: fix that the users data gets deleted, when deleting his account
- [ ] 2: integrate the recovery questions and answers
- [ ] 3: find a good solution for the client-system (i.e. web is not a client)
- [ ] 4: complete the account-manipulation page
- [ ] 5: write an API
- [ ] 6: make an admin console with stats
- [ ] 7: add media queries / optimize for mobiles
- [ ] 8: make the server faster / more performant (i.e. redesign the page display system, smash every return value in the users session and let the page be displayed by this value, so just use redirects and not custom renders anymore)
- [x] ~~9: find a better solution for the account-system (which page gets displayed to the user, and so on...)~~
- [ ] 10: add some good amount of encryption (encrypt the database serversided, and
 maybe during the transfer using private and public keys?)
- [x] 11: better input sanitation to prevent sql-inject-like attacks

**customisation to-do's** (those are to-do's that need to be implemented, to customize the server):

- [ ] 1: make page content modular (config.yml)
- [ ] 2: make colors modular

**final to-do's** (to-do's that need to be done to finalize the project):

- [ ] 1: get the code conventions / styles right according to PEP-8
- [ ] 2: delete empty html lines, so it looks like native html
- [ ] 3: migrate Flask to a WSGI-Server with ssl
- [ ] 4: host it on i.e. pythonanywhere
- [ ] 5: publish the API (pypi "easyserver" is name-squatted by me, sry for that)
- [ ] 6: write some docs
- [ ] 7: show it to my informatics teacher
